### ISSUE TITLE
Ulterius server has stopped working

### ISSUE THREAD

**Issue by kirkb927** [StrikeOrg/ulterius-server#46]
I have received this error since my PC did the Windows 10 anniversary update. I have uninstalled reinstalled Ulterius and updated Java. 

![image](https://cloud.githubusercontent.com/assets/22544226/18992518/b7c98c1e-86ec-11e6-8f0c-a1803ef1dbcf.png)

Application: Ulterius Server.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.SEHException
   at System.Net.UnsafeNclNativeMethods.SetFileCompletionNotificationModes(System.Runtime.InteropServices.CriticalHandle, FileCompletionNotificationModes)
   at System.Net.HttpListener.CreateRequestQueueHandle()
   at System.Net.HttpListener.Start()
   at UlteriusServer.WebServer.HttpServer+<Listen>d__15.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[[UlteriusServer.WebServer.HttpServer+<Listen>d__15, Ulterius Server, Version=1.1.0.8, Culture=neutral, PublicKeyToken=null]](Listen>d__15 ByRef)
   at UlteriusServer.WebServer.HttpServer.Listen()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-09-30T12:48:50.488923400Z" /> 
  <EventRecordID>2376</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>EnvyOffice</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Ulterius Server.exe</Data> 
  <Data>1.1.0.8</Data> 
  <Data>57d7e023</Data> 
  <Data>LavasoftTcpService64.dll</Data> 
  <Data>2.3.4.7</Data> 
  <Data>555dc671</Data> 
  <Data>c000001d</Data> 
  <Data>000000000000890d</Data> 
  <Data>20ec</Data> 
  <Data>01d21b18fc930d9a</Data> 
  <Data>C:\Program Files (x86)\Ulterius\Ulterius Server\Ulterius Server.exe</Data> 
  <Data>C:\WINDOWS\system32\LavasoftTcpService64.dll</Data> 
  <Data>8cc401f5-2d1b-4503-8982-61f275e0ec3e</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by andrewmd5** [comment]
Can you please post the contents of the unhandled exception logs located in the server app data folder.

**Comment by kirkb927** [comment]
I do not see any Data folder. TIA
![ulterius error 2](https://cloud.githubusercontent.com/assets/22544226/19090541/fac31cde-8a4c-11e6-8076-963f126da9d3.GIF)

**Comment by andrewmd5** [comment]
It's located in \AppData\Roaming\Ulterius\Ulterius Server\Logs\

**Comment by kirkb927** [comment]
Server log      Logs Ready
Set Startup
Loading Webcams
1 cameras loaded
Setting up HTTP Server
Web Server is running on this port: 22006
Creating system service

Log folder just contains TRACES

![ulterius error 3](https://cloud.githubusercontent.com/assets/22544226/19091078/1904a5a8-8a4f-11e6-874e-94ecadd61e39.GIF)

**Comment by kirkb927** [comment]
Is there another log somewhere that will have the information ?

**Comment by andrewmd5** [comment]
@kirkb927 It seems your server is starting fine now? I can see it says listening in your logs, is it still crashing?

**Comment by kirkb927** [comment]
Thank you for your time replying to me here is a screen grab of the error as it happens
![ulter](https://cloud.githubusercontent.com/assets/22544226/19094577/ba46b294-8a5e-11e6-93f2-ab3749d07123.gif)

**Comment by andrewmd5** [comment]
Hi @kirkb927 

It seems you have software conflicting with your installation of Ulterius, do you happen to have http://www.webcompanion.com/ installed? It seems it is trying to attach to our process and crashing it.  "LavasoftTcpService64"

**Comment by kirkb927** [comment]
No I do not have Webcompanion installed I do have Ad-block extensions installed in chrome.

**Comment by andrewmd5** [comment]
This doesn't seem to be an isolated issue, check your installed programs and see if anything from Lavasoft is running.  Ad-Aware is another application

**Comment by kirkb927** [comment]
I have no add Ad aware installed. I located the "LavasoftTcpService64" deleted it, uninstalled Ulterius, rebooted, Reinstalled Ulterius server.. same issue

**Comment by andrewmd5** [comment]
Please try temporarily disabling your anti virus and closing out any unnecessary programs and confirm Lavasoft is still not on your computer. Then post the new crash dump. 

The crash that you're reporting appears to originate from Lavasoft's LavasoftTcpService64.dll component.

**Comment by andrewmd5** [comment]
Please follow the steps in this thread

https://forums.malwarebytes.org/topic/184574-i-have-been-blessed-with-lavasofttcpservice64dll/
