### ISSUE TITLE
Terminal creation timeout

### ISSUE THREAD

**Issue by Taapo** [StrikeOrg/ulterius-server#59]
When I try to create a new terminal, either using cmd.exe or powershell -- I get a "terminal creation timeout" error.

**Comment by andrewmd5** [comment]
Can you please browse the logs located at 

C:\Windows\System32\config\systemprofile\AppData\Roaming\Ulterius\Ulterius Server\

And paste your server.log here and any files in the Exceptions folder

**Comment by reefbarman** [comment]
I have the same issue but I don't have the location you mentioned on my system. There isn't an Ulterius directory in C:\Windows\System32\config\systemprofile\AppData\Roaming

**Comment by TenetNoctis** [comment]
> Logs Ready
desktop duplication setup
1.9.5.0
Loading Webcams
Extracting client archive
Setting up HTTP Server
Web Server is running on this port: 22006
Creating system service
Service: TrueDesktop Task is running on thread: 12752
Desktop switched from  to Default on thread 3480
56 packet handlers loaded!
Getting ready to scan
scanning C:/
Cron Daemon Started
System.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\Octopodal Solutions\Ulterius\client.zip' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at UlteriusServer.Api.Services.Update.UpdateService.<CheckForClientUpdates>d__4.MoveNext() in E:\Dev\Ulterius\server\RemoteTaskServer\Api\Services\Update\UpdateService.cs:line 98
Checking for Updates
Api Server started at 0.0.0.0
Starting Terminal API
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at UlteriusServer.Api.Services.Update.UpdateService.CheckForServerUpdates() in E:\Dev\Ulterius\server\RemoteTaskServer\Api\Services\Update\UpdateService.cs:line 58
   at UlteriusServer.Api.Services.Update.UpdateService.<Updater>d__1.MoveNext() in E:\Dev\Ulterius\server\RemoteTaskServer\Api\Services\Update\UpdateService.cs:line 41
The system cannot find the file specified
Terminal Server bound to 0.0.0.0:22008
Trying to forward ports
No NAT Device Found
Client deleted
Connection from 127.0.0.1:49277
Service Manager Started
Manager started for 22010
Manager started for 22009
Disconnection from 127.0.0.1:49277
Connection from 127.0.0.1:49284
Disconnection from 127.0.0.1:49278
Connection from 127.0.0.1:49286
Connection from 127.0.0.1:49285
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
Packet failed to decrypt: Value cannot be null.
Parameter name: s
AES not shook, cannot create terminal
Disconnection from 127.0.0.1:49284
Connection from 127.0.0.1:49290
Service Manager Started
Manager started for 22010
Manager started for 22009
scanning E:/
scanning H:/
Disconnection from 127.0.0.1:49292
Connection from 127.0.0.1:49327
Service Manager Started
Manager started for 22010
Manager started for 22009
Connection from 192.168.1.3:38223
Service Manager Started
Manager started for 22009
Manager started for 22010
Disconnection from 192.168.1.3:38223
Connection from 192.168.1.3:38253
Service Manager Started
Manager started for 22009
Manager started for 22010
Screen Share Died
AES not shook, cannot create terminal
AES not shook, cannot create terminal
Desktop switched from Default to Winlogon on thread 3480
Desktop switched from Winlogon to Default on thread 3480
Disconnection from 192.168.1.3:43267
Connection from 192.168.1.3:38287
Service Manager Started
Manager started for 22010
Manager started for 22009
Disconnection from 127.0.0.1:49329
