### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Cr4xy** [StrikeOrg/ulterius-server#63]
Hello, since the new release my ulterius crashes when I start it up, or after I'm logged in.

The Exception:
System.Runtime.Serialization.SerializationException: The member `errorCode` was not found.
StackTrace:
```
   at System.Runtime.Serialization.SerializationInfo.GetElement(String name, Type& foundType)
   at System.Runtime.Serialization.SerializationInfo.GetInt32(String name)
   at Open.Nat.MappingException.GetObjectData(SerializationInfo info, StreamingContext context)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(JsonWriter writer, ISerializable value, JsonISerializableContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(JsonWriter writer, ISerializable value, JsonISerializableContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting)
   at UlteriusServer.Utilities.ExceptionHandler.UnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs e) in D:\\Documents\\StrikeTaskManager\\RemoteTaskServer\\Utilities\\ExceptionHandler.cs:Zeile 117.
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()
```

-----

Here I have the server.log with another exception:
```
Logs Ready
1.8.0.0
Loading Webcams
Setting up HTTP Server
Web Server is running on this port: 22006
Creating system service
56 packet handlers loaded!
Cron Daemon Started
Api Server started at 0.0.0.0
Starting Terminal API
Not supported 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at UlteriusServer.Api.Services.LocalSystem.SystemService.GetDriveInformation() in D:\Documents\StrikeTaskManager\RemoteTaskServer\Api\Services\LocalSystem\SystemService.cs:Zeile 532.
Terminal Server bound to 0.0.0.0:22008
Trying to forward ports
Checking for Updates
Starting notify icon
Not supported 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at UlteriusServer.Api.Services.LocalSystem.SystemService.GetDriveInformation() in D:\Documents\StrikeTaskManager\RemoteTaskServer\Api\Services\LocalSystem\SystemService.cs:Zeile 532.
Not supported 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at UlteriusServer.Api.Services.LocalSystem.SystemService.GetDriveInformation() in D:\Documents\StrikeTaskManager\RemoteTaskServer\Api\Services\LocalSystem\SystemService.cs:Zeile 532.
```

**Comment by andrewmd5** [comment]
Pushed a new update to solve this
